/* EJECUTAR COMO ROOT */
CREATE USER SAEM IDENTIFIED BY 'SAEM';
CREATE DATABASE SAEM CHARACTER SET = UTF8;
GRANT ALL PRIVILEGES ON SAEM.* TO 'SAEM';
COMMIT;
FLUSH PRIVILEGES;


/* EJECUTAR DENTRO DE LA BASE DE DATOS SAEM */
CREATE TABLE SAEM.ROL(
	ROL_ID INT NOT NULL AUTO_INCREMENT,
    ROL_NOMBRE VARCHAR(80),
    PRIMARY KEY (ROL_ID)
)CHARSET=UTF8;
CREATE UNIQUE INDEX IDX_ROL ON SAEM.ROL(ROL_NOMBRE);

CREATE TABLE SAEM.USUARIO(
	USUARIO_ID INT NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(80),
    PASSWORD VARCHAR(80),
    EMAIL VARCHAR(50),
    ROL_ID INT DEFAULT 2,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    PRIMARY KEY (USUARIO_ID)
)CHARSET=UTF8;
CREATE UNIQUE INDEX IDX_USUARIO ON SAEM.USUARIO(USUARIO);
ALTER TABLE SAEM.USUARIO ADD CONSTRAINT FOREIGN KEY (ROL_ID) REFERENCES SAEM.ROL(ROL_ID);

CREATE TABLE SAEM.ALUMNO(
	ALUMNO_ID INT NOT NULL AUTO_INCREMENT,
	AP_PATERNO VARCHAR(60),
    AP_MATERNO VARCHAR(60),
    ALUMNO_NOMBRE VARCHAR(60),
    FECHA_INGRESO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MATRICULA VARCHAR(20),
	FECHA_NACIMIENTO DATE,
	ESCUELA_PROCEDENCIA VARCHAR(150),
	ALUMNO_DIRECCION VARCHAR(300),
	ALUMNO_TELEFONO VARCHAR(10),
	TUTOR_NOMBRE VARCHAR(60),
	TUTOR_TELEFONO VARCHAR(60),
    PRIMARY KEY(ALUMNO_ID)
)CHARSET=UTF8;

CREATE TABLE SAEM.CAT_NIVEL(
	NIVEL_ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(30),
    PRIMARY KEY(NIVEL_ID)
)CHARSET=UTF8;

CREATE TABLE SAEM.CAT_CURSO(
	CATCURSO_ID INT NOT NULL AUTO_INCREMENT,
	NIVEL_ID INT,
    NOMBRE VARCHAR(30),
	DURACION VARCHAR(100),
    PRIMARY KEY(CATCURSO_ID)
)CHARSET=UTF8;
ALTER TABLE SAEM.CAT_CURSO ADD CONSTRAINT FOREIGN KEY (NIVEL_ID) REFERENCES SAEM.CAT_NIVEL(NIVEL_ID);

CREATE TABLE SAEM.CAT_TURNO(
	TURNO_ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(30),
	PRIMARY KEY(TURNO_ID)
)CHARSET=UTF8;

CREATE TABLE SAEM.CURSO(
	CURSO_ID INT NOT NULL AUTO_INCREMENT,
	CATCURSO_ID INT NOT NULL,
	TURNO_ID INT NOT NULL,
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
    INVERSION DECIMAL(7,2),
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(CURSO_ID)
)CHARSET=UTF8;
ALTER TABLE SAEM.CURSO ADD CONSTRAINT FOREIGN KEY (CATCURSO_ID) REFERENCES SAEM.CAT_CURSO(CATCURSO_ID);
ALTER TABLE SAEM.CURSO ADD CONSTRAINT FOREIGN KEY (TURNO_ID) REFERENCES SAEM.CAT_TURNO(TURNO_ID);

CREATE TABLE SAEM.ALUMNO_CURSO(
	ALUMNO_ID INT,
	CURSO_ID INT,
	ACTIVO TINYINT(1),
    FECHA_INSCRIPCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ALUMNO_ID,CURSO_ID)
)CHARSET=UTF8;

COMMIT;

/* ROLES DEFAULT */
INSERT INTO SAEM.ROL (ROL_NOMBRE) VALUES ('ADMINISTRADOR');
INSERT INTO SAEM.ROL (ROL_NOMBRE) VALUES ('USUARIO');

/* NIVELES DEFAULT */
INSERT INTO SAEM.CAT_NIVEL (NOMBRE) VALUES ('UNIVERSIDAD');
INSERT INTO SAEM.CAT_NIVEL (NOMBRE) VALUES ('BACHILLERATO');
INSERT INTO SAEM.CAT_NIVEL (NOMBRE) VALUES ('SECUNDARIA');
INSERT INTO SAEM.CAT_NIVEL (NOMBRE) VALUES ('MATHEMATICS');

/* CATALOGO DE CURSOS */
	/* UNIVERSIDAD */ 
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'U. P','8 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'UNAM','12 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'UNAM ON LINE','12 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'DEFENSA','10 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'UV','8 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'UV ON LINE','8 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'BUAP','11 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'IPN','10 SEMANAS');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (1,'BENV','10 SEMANAS');
	/* BACHILLERATO */
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (2,'BACHILLERATO','8 SEMANAS');
	/* SECUNDARIA */
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (3,'SECUNDARIA','8 SEMANAS');
	/* MATHEMATICS */
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (4,'REGULARIZACIÓN','TODO EL AÑO');
INSERT INTO SAEM.CAT_CURSO (NIVEL_ID,NOMBRE,DURACION) VALUES (4,'CURSO DE VERANO','4 SEMANAS');

/* CATALOGO DE TURNOS */
INSERT INTO SAEM.CAT_TURNO (NOMBRE) VALUES ('MATUTINO');
INSERT INTO SAEM.CAT_TURNO (NOMBRE) VALUES ('VESPERTINO');
INSERT INTO SAEM.CAT_TURNO (NOMBRE) VALUES ('SABATINO');
INSERT INTO SAEM.CAT_TURNO (NOMBRE) VALUES ('VIRTUAL');
	
/* USUARIO ADMINISTRADOR */
INSERT INTO SAEM.USUARIO (USUARIO,PASSWORD,EMAIL,ROL_ID,FECHA_CREACION,FECHA_MODIFICACION) VALUES ('admin',
'$2a$10$iK3zOFji.KQk1Aq50zT49.KP1HAXM9u8XSPevN0XgQ9s1tdMDJfSW', 'victor.ivan.cruzg@gmail.com',1,sysdate(),sysdate());
	
COMMIT;
